# 🚀 Deploy to JAFFA test website when pushing to any feature branch

name: 🚀 Deploy to test website on push

on:
  push:
    branches: [ 'feature/**' ]

  # Allows manual trigger
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: Test JAFFA

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      # Deploy files to test site via FTP
      - name: 📂 Sync files to test
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.ipswichjaffa.org.uk
          username: githubftp@test.ipswichjaffa.org.uk
          password: ${{ secrets.FtpServerPassword }}
          server-dir: public_html/wp-content/plugins/ipswich-jaffa-event-results/
          dry-run: false
          exclude: |
            **/.git*
            **/.git*/**
            api/config.php
